### ISSUE TITLE
Support Capability to Use GPUs

### ISSUE THREAD

**Issue by NickShahML** [atgambardella/pytorch-es#2]
Hey Andrew, thanks immensely for putting this together. Very useful example of evolution strategies. 

I was wondering what your thoughts of including GPU support. My thought is that any action done by each model can be ran on the gpu and the environment is then ran on the CPU. Due to the nature of the GPU batching, one idea is that you would batch actions, then let the environment respond, and continue this process.

I feel that the biggest bottleneck at this point would be pcie lanes depending on how much bandwidth you have to the GPU. The bottom line is that models would be stored on the gpu and would execute on the gpu while the env is ran on the cpu. Does `gym` allow the actual env to run on the gpu?

**Comment by atgambardella** [comment]
I'm doubtful that using the GPU could give you any speedups in this case for a few reasons:

1. Gym environments can't be run on the GPU, so we would have an unnecessary communication overhead
2. We can't batch anything since each worker has a different model
3. We only need forward passes through the network, and for SL, most of the time doing backprop is in the backward pass.

Adding GPU support is a very quick change though -- for any tensor `t` do `t = t.cuda()` and it should work.

**Comment by NickShahML** [comment]
Thanks andrew. The biggest question is if it would speed up computation time. Thanks for the insight!
